  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          username: chitranagad
          password: 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
          uri: https://github.com/chitranagad/cloud-config-server.git
          skip-ssl-validation: true
    
server:
  port: 9095
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost